Repository Polymer/pwa-starter-kit, pull requests merged in 2018-12, with the labels that each got.

#282 add 404 and 500 page
  404.html
  500.html
  main.py
Labels: cla: yes

#293 Redesiged layout.
  _layouts/default.html
  css/main.css
  css/theme.css
  images/logos/logo_email.svg
  images/logos/logo_github.svg
  images/logos/logo_slack.svg
  images/logos/logo_twitter.svg
  index.html
Labels: cla: yes

#294 Redesign
  _layouts/default.html
  css/main.css
Labels: cla: no

#295 Mention webpack branch; update browser support page
  browser-support.md
  faq.md
Labels: Area: docs, cla: yes

#297 Fix typo
  index.html
Labels: cla: yes

#296 Update deps
  package-lock.json
  package.json
Labels: cla: yes

#302 Update router.js
  test/integration/router.js
Labels: cla: yes

#306 [Docs] Properties of connected elts should be updated in `stateChange…
  redux-and-state-management.md
Labels: cla: yes
